
/*
 * This code is generated by grabman.py, better not to edit.
 */
#ifndef _JSH_MAN_H
#define _JSH_MAN_H


struct man {
    char    *cmd;
    char    *desc;
} man[] = { 

    {"id",                "print real and effective user and group IDs"},
    {"pwd",               "print name of current/working directory"},
    {"passwd",            "update user's authentication tokens"},
    {"uname",             "print system information"},
    {"ls",                "list directory contents"},
    {"mkdir",             "make directories"},
    {"rm",                "remove files or directories"},
    {"rmdir",             "remove empty directories"},
    {"touch",             "change file timestamps"},
    {"cp",                "copy files and directories"},
    {"tar",               "manual page for tar 1.26"},
    {"zip",               "package and compress (archive) files"},
    {"unzip",             "list, test and extract compressed files in a ZIP archive"},
    {"vim",               "Vi IMproved, a programmers text editor"},
    {"cat",               "concatenate files and print on the standard output"},
    {"more",              "file perusal filter for crt viewing"},
    {"tail",              "output the last part of files"},
    {"grep",              "print lines matching a pattern"},
    {"ssh",               "OpenSSH SSH client (remote login program)"},
    {"ping",              "send ICMP ECHO_REQUEST to network hosts"},
    {"traceroute",        "print the route packets trace to network host"},
    {"scp",               "secure copy (remote file copy program)"},
    {"sftp",              "secure file transfer program"},
    {"wget",              "The non-interactive network downloader."},
    {"curl",              "transfer a URL"},
    {"crontab",           "maintains crontab files for individual users"},
    {NULL,                NULL}

};


#endif  /* _JSH_MAN_H */

